name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install cpp
      run: |
        sudo apt update -y
        sudo apt install -y gcc-11 g++-11
        g++-11 --version
    - name: make
      run: CXX=g++-11 make
