name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install cpp
      run: |
        sudo apt update -y
        sudo apt install -y gcc-10 g++-10
    - name: make
      run: CXX=g++-10 make
